version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:test@postgres:5432/postgres
      HASURA_GRAPHQL_ENDPOINT: http://localhost:8080
    restart: always
volumes:
  db_data:
